stages:
  get_data:
    cmd: python src/get_data.py
    deps:
    - src/get_data.py
    outs:
    - data/raw/SeoulBikeData.csv
  prepare:
    cmd: python src/prepare.py data/raw/SeoulBikeData.csv
    deps:
    - data/raw/SeoulBikeData.csv
    - src/prepare.py
    outs:
    - data/processed/test.csv
    - data/processed/train.csv
  train:
    cmd: python src/train.py data/processed/train.csv
    deps:
    - data/processed/train.csv
    - src/train.py
    outs:
    - models/xgb_model.pkl
  evaluate:
    cmd: python src/evaluate.py models/xgb_model.pkl data/processed
    deps:
    - data/processed
    - models/xgb_model.pkl
    - src/evaluate.py
    metrics:
    - metrics/metrics.json:
        cache: false
